### ISSUE TITLE
Watch mode: auto-adopt new files appearing in --mib-dir

### ISSUE THREAD

**Issue by tosumitdhaka** [tosumitdhaka/trishul-smi#29]
## Problem
v0.5.0 watch mode only prints a one-line notice when a new file appears in `--mib-dir` mid-watch (documented v1 limitation) — the new MIB is neither compiled nor watched.

## Proposed solution
Adopt the new file: add it to the cumulative watch set, run an initial compile for it, and announce the result. File removal stays notice-only (separate design question).

## Tests to add
- A fixture MIB written into `--mib-dir` mid-watch is compiled (output appears) and watched from the next cycle.

Ref: docs/plans/v0.5.1_plan.md item 4. Target: v0.5.1.

**Comment by tosumitdhaka** [comment]
Shipped in v0.5.1 (0875440): new files in `--mib-dir` mid-watch are adopted (watch set + debounced initial compile; unparseable files → failed row, watcher survives). Documented limitations from the pre-tag review: a module that failed on an unresolved import is not recompiled when the missing dependency is later adopted (recompiles on its own change); removal stays notice-only.
